apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: app
  labels:
    app.kubernetes.io/name: app
spec:
  rules:
    - host: app.k8s.swordfishsecurity.com
      http:
        paths:
        - path: /
          backend:
            serviceName: app
            servicePort: 5000
        - path: /[.]*
          backend:
            serviceName: app2
            servicePort: 5000
        - path: /two
          backend:
            serviceName: app
            servicePort: 5000
        - path: /admin
          backend:
            serviceName: app
            servicePort: 5000

